markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: TencentLocation's Blog
description: TencentLocation's Blog, powered by Jekyll...
# feed: http://www.winfirm.cn/atom.xml

author: TencentLocation

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
